version: "3.9"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - network.host=0.0.0.0
      - node.name=es01
    # volumes:
    #   - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "${ELASTIC_PORT:-9200}:9200"
    network_mode: host
    # networks:
    #   - elastic
    restart: always
  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.1
    environment:
      - ELASTICSEARCH_HOSTS=http://localhost:9200
    network_mode: host
    depends_on:
      - elasticsearch
    # networks:
    #   - elastic
    restart: always
  
  packetbeat-dashboards:
    image: docker.elastic.co/beats/packetbeat:8.16.1
    command: setup --dashboards
    user: root
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    depends_on:
      - elasticsearch
      - kibana
  packetbeat:
    image: docker.elastic.co/beats/packetbeat:8.16.1
    network_mode: host
    user: root
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./packetbeat.yml:/usr/share/packetbeat/packetbeat.yml
    depends_on:
      - elasticsearch
    restart: unless-stopped
  

# networks:
#   elastic:
#     driver: bridge

# volumes:
#   elasticsearch-data:
